var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/chat/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tfodgo._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_114i_g0.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cyhyu4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03.bhr3._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0j3yapm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_0zlmp.~._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_chat_page_actions_07js-tw.js")
R.m(33429)
module.exports=R.m(33429).exports
