var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0r_d4js._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0smgx8w.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cyhyu4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03.bhr3._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0j3yapm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_0zlmp.~._.js")
R.c("server/chunks/ssr/src_0ehb-ah._.js")
R.c("server/chunks/ssr/src_lib_utils_ts_0cn8qfr._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_dashboard_page_actions_0q.i2d_.js")
R.m(32847)
module.exports=R.m(32847).exports
